version: 2

jobs:
  build_dev:
    docker:
      - image: circleci/php:5.6-cli-node-browsers
    steps:
      - checkout
      - run:
          name: Cloning Git Repository
          command: git clone git@github.com:bansnoob/garagebox.git /home/circleci/garagebox

#      - run:
#          name: Installing sshpass
#          command: sudo apt-get install sshpass

#      - run:
#          name: Adding domain to know hosts
#          command: ssh-keyscan -H 54.193.238.27 >> ~/.ssh/known_hosts

#      - run:
#          name: Moving to Beta
#          command: sshpass -p $GB_PASS rsync -rlOtvz -e ssh /home/circleci/lmHObWgcHzmFMaAO/ $GB_USER@54.193.238.27:/var/www/html/lmHObWgcHzmFMaAO/

workflows:
  version: 2
  build_flow:
    jobs:
      - build_dev:
          filters:
            branches:
              only: developp