version: 2

jobs:
  build_dev:
    docker:
      - image: circleci/php:5.6-cli-node-browsers
    steps:
      - checkout
      - add_shh_keys:
          fingerprints:
            - "29:1a:31:90:bb:cd:c5:aa:4b:73:a2:6d:d9:f8:99:24"
            
      - run:
          name: Cloning Git Repository
          command: git clone git@github.com:bansnoob/garagebox.git /home/circleci/garagebox

#      - run:
#          name: Installing sshpass
#          command: sudo apt-get install sshpass

      - run:
          name: Adding domain to know hosts
          command: ssh-keyscan -H 3.142.166.23 >> ~/.ssh/known_hosts

      - run:
          name: Moving to Beta
          command: rsync -rlOtvz -e 'ssh -v' /home/circleci/garagebox/ $GB_USER@3.142.166.23:/var/www/html/

workflows:
  version: 2
  build_flow:
    jobs:
      - build_dev:
          filters:
            branches:
              only: developp